version: "3.9"
services:
  mongo:
    image: mongo:7
    environment:
      MONGO_INITDB_ROOT_USERNAME: featuregate
      MONGO_INITDB_ROOT_PASSWORD: featuregate
      MONGO_INITDB_DATABASE: featuregate
    ports:
      - 27017:27017
    volumes:
      - mongodata:/data/db
volumes:
  mongodata:
